version: '3'
services:
  develop:
    image: fpco/stack-build-small
    volumes:
    - .:/code
    working_dir: /code
    command: ["bash"]

  web:
    image: fpco/stack-build-small
    #   build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    working_dir: /code
    command: ["/bin/bash", "./bin/run.sh"]
  #   - logvolume01:/var/log
  #   links:
  #   - redis
  # redis:
  #   image: redis
# volumes:
  # logvolume01: {}